Move and improve code to find issues detected by CodeQL in its .sarif file

diff --git a/.github/workflows/linters.yml b/.github/workflows/linters.yml
--- a/.github/workflows/linters.yml
+++ b/.github/workflows/linters.yml
@@ -83,9 +83,6 @@ jobs:
         do
           "$CODEQL_BIN" database analyze codeql-result-database/"$LANG"/ --sarif-category="$LANG" --output=out-"$LANG".sarif --format=sarif-latest --threads=0 ;
         done ;
-    - name: Search for startLine to see if any issues are found
-      if: startsWith(runner.os, 'Linux')
-      run: grep --context=11 startLine out-*.sarif || true ;
     - name: Upload codeql results to public GitHub repo or private repo on an enterprise plan
       if: startsWith(runner.os, 'Linux')
       run: |
@@ -96,4 +93,9 @@ jobs:
         done ;
       env:
         CODEQL_TOKEN: ${{ secrets.CODEQL_UPLOAD_TOKEN }}
+    # grep returns exit code 1 if string is not found but specified file is present
+    # grep returns exit code 2 if specified file is not present
+    - name: Look for startLine to see if any issues are found, if so, return exit code 1
+      if: startsWith(runner.os, 'Linux')
+      run: grep --context=11 startLine out-*.sarif ; EXIT_CODE=$? ; if [ "$EXIT_CODE" -eq 0 ]; then echo ERROR ; fi ;
     # CodeQL analysis section END
